CREATE TABLE PAIS (
    IDPais SERIAL PRIMARY KEY,
    NomPais VARCHAR(100) NOT NULL
);

CREATE TABLE ESTADO (
    IDEstado SERIAL PRIMARY KEY,
    NomEstado VARCHAR(100) NOT NULL,
    fk_PAIS INT NOT NULL,

    CONSTRAINT FK_ESTADO_PAIS
        FOREIGN KEY (fk_PAIS)
        REFERENCES PAIS(IDPais)
);

CREATE TABLE CIDADE (
    IDCidade SERIAL PRIMARY KEY,
    NomCidade VARCHAR(100) NOT NULL,
    fk_ESTADO INT NOT NULL,

    CONSTRAINT FK_CIDADE_ESTADO
        FOREIGN KEY (fk_ESTADO)
        REFERENCES ESTADO(IDEstado)
);

CREATE TABLE CONTA (
    IDConta SERIAL PRIMARY KEY,
    EmailConta VARCHAR(255) UNIQUE NOT NULL,
    SenhaConta VARCHAR(255) NOT NULL,
    DtCrcaoConta DATE NOT NULL,
    fk_CIDADE INT,

    CONSTRAINT FK_CONTA_CIDADE
        FOREIGN KEY (fk_CIDADE)
        REFERENCES CIDADE(IDCidade)
);

CREATE TABLE PESSOAL (
    fk_CONTA INT PRIMARY KEY,
    NomPsso VARCHAR(100) NOT NULL,
    SobnomPsso VARCHAR(100) NOT NULL,
    TtloProfPsso VARCHAR(150),

    CONSTRAINT FK_PESSOAL_CONTA
        FOREIGN KEY (fk_CONTA)
        REFERENCES CONTA(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE CORPORATIVA (
    fk_CONTA INT PRIMARY KEY,
    NomComerc VARCHAR(150) NOT NULL,
    NumFuncEmp INT,
    DescriEmp TEXT,

    CONSTRAINT FK_CORPORATIVA_CONTA
        FOREIGN KEY (fk_CONTA)
        REFERENCES CONTA(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE CORPORATIVA_SETOREMP (
    SetorEmp VARCHAR(100) PRIMARY KEY,
    fk_CORPORATIVA INT NOT NULL,

    CONSTRAINT FK_SETOR_CORPORATIVA
        FOREIGN KEY (fk_CORPORATIVA)
        REFERENCES CORPORATIVA(fk_CONTA)
        ON DELETE CASCADE
);

CREATE TABLE COMPETENCIA (
    IDComp SERIAL PRIMARY KEY,
    NomeComp VARCHAR(100) NOT NULL
);

CREATE TABLE IDIOMA (
    IDIdioma SERIAL PRIMARY KEY,
    NomeIdioma VARCHAR(100) NOT NULL
);

CREATE TABLE FORMACAOACAD (
    IDForm SERIAL PRIMARY KEY,
    NomInstitForm VARCHAR(150) NOT NULL,
    GrauForm VARCHAR(100),
    AreaForm VARCHAR(100),
    DtInicioForm DATE,
    DtFimForm DATE,
    fk_PESSOAL INT NOT NULL,

    CONSTRAINT FK_FORMACAO_PESSOAL
        FOREIGN KEY (fk_PESSOAL)
        REFERENCES PESSOAL(fk_CONTA)
        ON DELETE CASCADE
);

CREATE TABLE EXPERIENCIAPROF (
    IDExp SERIAL PRIMARY KEY,
    TituloExp VARCHAR(150) NOT NULL,
    TipoEmpregoExp VARCHAR(100),
    DtInicioExp DATE,
    DtFimExp DATE,
    DescAtv TEXT,
    fk_PESSOAL INT NOT NULL,
    fk_CORPORATIVA INT,

    CONSTRAINT FK_EXPERIENCIA_PESSOAL
        FOREIGN KEY (fk_PESSOAL)
        REFERENCES PESSOAL(fk_CONTA)
        ON DELETE CASCADE,

    CONSTRAINT FK_EXPERIENCIA_CORPORATIVA
        FOREIGN KEY (fk_CORPORATIVA)
        REFERENCES CORPORATIVA(fk_CONTA)
);

CREATE TABLE VAGAEMPREGO (
    IDVagaEmp SERIAL PRIMARY KEY,
    TtloVaga VARCHAR(150) NOT NULL,
    DescriVaga TEXT,
    FormatoTrabVaga VARCHAR(50),
    DtCrcaoVaga DATE,
    fk_CORPORATIVA INT NOT NULL,

    CONSTRAINT FK_VAGA_CORPORATIVA
        FOREIGN KEY (fk_CORPORATIVA)
        REFERENCES CORPORATIVA(fk_CONTA)
        ON DELETE CASCADE
);

CREATE TABLE POST (
    IDPost SERIAL PRIMARY KEY,
    DtPubliPost TIMESTAMP NOT NULL,
    ConteudoPost TEXT NOT NULL,
    NivelVisib VARCHAR(50),
    fk_CONTA INT NOT NULL,

    CONSTRAINT FK_POST_CONTA
        FOREIGN KEY (fk_CONTA)
        REFERENCES CONTA(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE COMENTARIO (
    IDComentario SERIAL PRIMARY KEY,
    ConteudoTxtCom TEXT NOT NULL,
    DtPubliCom TIMESTAMP NOT NULL,
    fk_POST INT NOT NULL,
    fk_CONTA INT NOT NULL,

    CONSTRAINT FK_COMENTARIO_POST
        FOREIGN KEY (fk_POST)
        REFERENCES POST(IDPost)
        ON DELETE CASCADE,

    CONSTRAINT FK_COMENTARIO_CONTA
        FOREIGN KEY (fk_CONTA)
        REFERENCES CONTA(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE REAGEPOST (
    DtReacao TIMESTAMP NOT NULL,
    TipoReacao VARCHAR(50) NOT NULL,
    fk_CONTA INT NOT NULL,
    fk_POST INT NOT NULL,

    PRIMARY KEY (fk_CONTA, fk_POST),

    CONSTRAINT FK_REAGEPOST_CONTA
        FOREIGN KEY (fk_CONTA)
        REFERENCES CONTA(IDConta)
        ON DELETE CASCADE,

    CONSTRAINT FK_REAGEPOST_POST
        FOREIGN KEY (fk_POST)
        REFERENCES POST(IDPost)
        ON DELETE CASCADE
);

CREATE TABLE POSSCOMP (
    fk_COMPETENCIA INT NOT NULL,
    fk_PESSOAL INT NOT NULL,

    PRIMARY KEY (fk_COMPETENCIA, fk_PESSOAL),

    CONSTRAINT FK_POSSCOMP_COMP
        FOREIGN KEY (fk_COMPETENCIA)
        REFERENCES COMPETENCIA(IDComp)
        ON DELETE CASCADE,

    CONSTRAINT FK_POSSCOMP_PESSOAL
        FOREIGN KEY (fk_PESSOAL)
        REFERENCES PESSOAL(fk_CONTA)
        ON DELETE CASCADE
);

CREATE TABLE FORMPOSSCOMP (
    fk_COMPETENCIA INT NOT NULL,
    fk_FORMACAOACAD INT NOT NULL,

    PRIMARY KEY (fk_COMPETENCIA, fk_FORMACAOACAD),

    CONSTRAINT FK_FORMPOSSCOMP_COMP
        FOREIGN KEY (fk_COMPETENCIA)
        REFERENCES COMPETENCIA(IDComp)
        ON DELETE CASCADE,

    CONSTRAINT FK_FORMPOSSCOMP_FORM
        FOREIGN KEY (fk_FORMACAOACAD)
        REFERENCES FORMACAOACAD(IDForm)
        ON DELETE CASCADE
);

CREATE TABLE EXPPOSSCOMP (
    fk_COMPETENCIA INT NOT NULL,
    fk_EXPERIENCIAPROF INT NOT NULL,

    PRIMARY KEY (fk_COMPETENCIA, fk_EXPERIENCIAPROF),

    CONSTRAINT FK_EXPPOSSCOMP_COMP
        FOREIGN KEY (fk_COMPETENCIA)
        REFERENCES COMPETENCIA(IDComp)
        ON DELETE CASCADE,

    CONSTRAINT FK_EXPPOSSCOMP_EXP
        FOREIGN KEY (fk_EXPERIENCIAPROF)
        REFERENCES EXPERIENCIAPROF(IDExp)
        ON DELETE CASCADE
);

CREATE TABLE FALAIDIOM (
    NvlProfic VARCHAR(50),
    fk_IDIOMA INT NOT NULL,
    fk_PESSOAL INT NOT NULL,

    PRIMARY KEY (fk_IDIOMA, fk_PESSOAL),

    CONSTRAINT FK_FALAIDIOM_IDIOMA
        FOREIGN KEY (fk_IDIOMA)
        REFERENCES IDIOMA(IDIdioma)
        ON DELETE CASCADE,

    CONSTRAINT FK_FALAIDIOM_PESSOAL
        FOREIGN KEY (fk_PESSOAL)
        REFERENCES PESSOAL(fk_CONTA)
        ON DELETE CASCADE
);

CREATE TABLE APLICAAVAGA (
    DtAplccao TIMESTAMP NOT NULL,
    SttusAplccao VARCHAR(50),
    fk_VAGAEMPREGO INT NOT NULL,
    fk_PESSOAL INT NOT NULL,

    PRIMARY KEY (fk_VAGAEMPREGO, fk_PESSOAL),

    CONSTRAINT FK_APLICA_VAGA
        FOREIGN KEY (fk_VAGAEMPREGO)
        REFERENCES VAGAEMPREGO(IDVagaEmp)
        ON DELETE CASCADE,

    CONSTRAINT FK_APLICA_PESSOAL
        FOREIGN KEY (fk_PESSOAL)
        REFERENCES PESSOAL(fk_CONTA)
        ON DELETE CASCADE
);

CREATE TABLE CONEXAO (
    DtEnvConv TIMESTAMP NOT NULL,
    DtAceitConv TIMESTAMP,
    StatusConexao VARCHAR(50),
    fk_PESSOAL_1 INT NOT NULL,
    fk_PESSOAL_2 INT NOT NULL,

    PRIMARY KEY (fk_PESSOAL_1, fk_PESSOAL_2),

    CONSTRAINT FK_CONEXAO_PESSOAL1
        FOREIGN KEY (fk_PESSOAL_1)
        REFERENCES PESSOAL(fk_CONTA)
        ON DELETE CASCADE,

    CONSTRAINT FK_CONEXAO_PESSOAL2
        FOREIGN KEY (fk_PESSOAL_2)
        REFERENCES PESSOAL(fk_CONTA)
        ON DELETE CASCADE,

    CONSTRAINT CHK_CONEXAO_DIFERENTE
        CHECK (fk_PESSOAL_1 <> fk_PESSOAL_2)
);