DROP TABLE IF EXISTS PAIS CASCADE;
DROP TABLE IF EXISTS ESTADO CASCADE;
DROP TABLE IF EXISTS CIDADE CASCADE;
DROP TABLE IF EXISTS CONTA CASCADE;
DROP TABLE IF EXISTS PESSOAL CASCADE;
DROP TABLE IF EXISTS CORPORATIVA CASCADE;
DROP TABLE IF EXISTS CORPORATIVA_SETOREMP CASCADE;
DROP TABLE IF EXISTS COMPETENCIA CASCADE;
DROP TABLE IF EXISTS IDIOMA CASCADE;
DROP TABLE IF EXISTS FORMACAOACAD CASCADE;
DROP TABLE IF EXISTS EXPERIENCIAPROF CASCADE;
DROP TABLE IF EXISTS VAGAEMPREGO CASCADE;
DROP TABLE IF EXISTS POST CASCADE;
DROP TABLE IF EXISTS COMENTARIO CASCADE;
DROP TABLE IF EXISTS REAGEPOST CASCADE;
DROP TABLE IF EXISTS POSSCOMP CASCADE;
DROP TABLE IF EXISTS FORMPOSSCOMP CASCADE;
DROP TABLE IF EXISTS EXPPOSSCOMP CASCADE;
DROP TABLE IF EXISTS FALAIDIOM CASCADE;
DROP TABLE IF EXISTS APLICAAVAGA CASCADE;
DROP TABLE IF EXISTS CONEXAO CASCADE;

CREATE TABLE IF NOT EXISTS PAIS (
    IDPais INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NomPais VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ESTADO (
    IDEstado INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NomEstado VARCHAR(100) NOT NULL,
    IDPais INT NOT NULL,

    CONSTRAINT FK_ESTADO_PAIS
        FOREIGN KEY (IDPais)
        REFERENCES PAIS(IDPais)
);

CREATE TABLE IF NOT EXISTS CIDADE (
    IDCidade INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NomCidade VARCHAR(100) NOT NULL,
    IDEstado INT NOT NULL,

    CONSTRAINT FK_CIDADE_ESTADO
        FOREIGN KEY (IDEstado)
        REFERENCES ESTADO(IDEstado)
);

CREATE TABLE IF NOT EXISTS CONTA (
    IDConta INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EmailConta VARCHAR(255) UNIQUE NOT NULL,
    SenhaConta VARCHAR(255) NOT NULL,
    DtCrcaoConta DATE NOT NULL,
    IDCidade INT,

    CONSTRAINT FK_CONTA_CIDADE
        FOREIGN KEY (IDCidade)
        REFERENCES CIDADE(IDCidade)
);

CREATE TABLE IF NOT EXISTS PESSOAL (
    IDConta INT PRIMARY KEY,
    NomPsso VARCHAR(100) NOT NULL,
    SobnomPsso VARCHAR(100) NOT NULL,
    TtloProfPsso VARCHAR(150),

    CONSTRAINT FK_PESSOAL_CONTA
        FOREIGN KEY (IDConta)
        REFERENCES CONTA(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CORPORATIVA (
    IDConta INT PRIMARY KEY,
    NomComerc VARCHAR(150) NOT NULL,
    NumFuncEmp INT,
    DescriEmp TEXT,

    CONSTRAINT FK_CORPORATIVA_CONTA
        FOREIGN KEY (IDConta)
        REFERENCES CONTA(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CORPORATIVA_SETOREMP (
    SetorEmp VARCHAR(100) PRIMARY KEY,
    IDEmp INT NOT NULL,

    CONSTRAINT FK_SETOR_CORPORATIVA
        FOREIGN KEY (IDEmp)
        REFERENCES CORPORATIVA(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMPETENCIA (
    IDComp INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NomeComp VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS IDIOMA (
    IDIdioma INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NomeIdioma VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORMACAOACAD (
    IDForm INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NomInstitForm VARCHAR(150) NOT NULL,
    GrauForm VARCHAR(100),
    AreaForm VARCHAR(100),
    DtInicioForm DATE,
    DtFimForm DATE,
    IDConta INT NOT NULL,

    CONSTRAINT FK_FORMACAO_PESSOAL
        FOREIGN KEY (IDConta)
        REFERENCES PESSOAL(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EXPERIENCIAPROF (
    IDExp INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TituloExp VARCHAR(150) NOT NULL,
    TipoEmpregoExp VARCHAR(100),
    DtInicioExp DATE,
    DtFimExp DATE,
    DescAtv TEXT,
    IDConta INT NOT NULL,
    IDEmp INT,

    CONSTRAINT FK_EXPERIENCIA_PESSOAL
        FOREIGN KEY (IDConta)
        REFERENCES PESSOAL(IDConta)
        ON DELETE CASCADE,

    CONSTRAINT FK_EXPERIENCIA_CORPORATIVA
        FOREIGN KEY (IDEmp)
        REFERENCES CORPORATIVA(IDConta)
);

CREATE TABLE IF NOT EXISTS VAGAEMPREGO (
    IDVagaEmp INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TtloVaga VARCHAR(150) NOT NULL,
    DescriVaga TEXT,
    FormatoTrabVaga VARCHAR(50),
    DtCrcaoVaga DATE,
    IDEmp INT NOT NULL,

    CONSTRAINT FK_VAGA_CORPORATIVA
        FOREIGN KEY (IDEmp)
        REFERENCES CORPORATIVA(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE  IF NOT EXISTS POST (
    IDPost INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DtPubliPost TIMESTAMP NOT NULL,
    ConteudoPost TEXT NOT NULL,
    NivelVisib VARCHAR(50),
    IDConta INT NOT NULL,

    CONSTRAINT FK_POST_CONTA
        FOREIGN KEY (IDConta)
        REFERENCES CONTA(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMENTARIO (
    IDComentario INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ConteudoTxtCom TEXT NOT NULL,
    DtPubliCom TIMESTAMP NOT NULL,
    IDPost INT NOT NULL,
    IDConta INT NOT NULL,

    CONSTRAINT FK_COMENTARIO_POST
        FOREIGN KEY (IDPost)
        REFERENCES POST(IDPost)
        ON DELETE CASCADE,

    CONSTRAINT FK_COMENTARIO_CONTA
        FOREIGN KEY (IDConta)
        REFERENCES CONTA(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REAGEPOST (
    DtReacao TIMESTAMP NOT NULL,
    TipoReacao VARCHAR(50) NOT NULL,
    IDConta INT NOT NULL,
    IDPost INT NOT NULL,

    PRIMARY KEY (IDConta, IDPost),

    CONSTRAINT FK_REAGEPOST_CONTA
        FOREIGN KEY (IDConta)
        REFERENCES CONTA(IDConta)
        ON DELETE CASCADE,

    CONSTRAINT FK_REAGEPOST_POST
        FOREIGN KEY (IDPost)
        REFERENCES POST(IDPost)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS POSSCOMP (
    IDComp INT NOT NULL,
    IDConta INT NOT NULL,

    PRIMARY KEY (IDComp, IDConta),

    CONSTRAINT FK_POSSCOMP_COMP
        FOREIGN KEY (IDComp)
        REFERENCES COMPETENCIA(IDComp)
        ON DELETE CASCADE,

    CONSTRAINT FK_POSSCOMP_PESSOAL
        FOREIGN KEY (IDConta)
        REFERENCES PESSOAL(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FORMPOSSCOMP (
    IDComp INT NOT NULL,
    IDForm INT NOT NULL,

    PRIMARY KEY (IDComp, IDForm),

    CONSTRAINT FK_FORMPOSSCOMP_COMP
        FOREIGN KEY (IDComp)
        REFERENCES COMPETENCIA(IDComp)
        ON DELETE CASCADE,

    CONSTRAINT FK_FORMPOSSCOMP_FORM
        FOREIGN KEY (IDForm)
        REFERENCES FORMACAOACAD(IDForm)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EXPPOSSCOMP (
    IDComp INT NOT NULL,
    IDExp INT NOT NULL,

    PRIMARY KEY (IDComp, IDExp),

    CONSTRAINT FK_EXPPOSSCOMP_COMP
        FOREIGN KEY (IDComp)
        REFERENCES COMPETENCIA(IDComp)
        ON DELETE CASCADE,

    CONSTRAINT FK_EXPPOSSCOMP_EXP
        FOREIGN KEY (IDExp)
        REFERENCES EXPERIENCIAPROF(IDExp)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FALAIDIOM (
    NvlProfic VARCHAR(50),
    IDIdioma INT NOT NULL,
    IDConta INT NOT NULL,

    PRIMARY KEY (IDIdioma, IDConta),

    CONSTRAINT FK_FALAIDIOM_IDIOMA
        FOREIGN KEY (IDIdioma)
        REFERENCES IDIOMA(IDIdioma)
        ON DELETE CASCADE,

    CONSTRAINT FK_FALAIDIOM_PESSOAL
        FOREIGN KEY (IDConta)
        REFERENCES PESSOAL(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS APLICAAVAGA (
    DtAplccao TIMESTAMP NOT NULL,
    SttusAplccao VARCHAR(50),
    IDVagaEmp INT NOT NULL,
    IDConta INT NOT NULL,

    PRIMARY KEY (IDVagaEmp, IDConta),

    CONSTRAINT FK_APLICA_VAGA
        FOREIGN KEY (IDVagaEmp)
        REFERENCES VAGAEMPREGO(IDVagaEmp)
        ON DELETE CASCADE,

    CONSTRAINT FK_APLICA_PESSOAL
        FOREIGN KEY (IDConta)
        REFERENCES PESSOAL(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE  IF NOT EXISTS CONEXAO (
    DtEnvConv TIMESTAMP NOT NULL,
    DtAceitConv TIMESTAMP,
    StatusConexao VARCHAR(50),
    IDConta_1 INT NOT NULL,
    IDConta_2 INT NOT NULL,

    PRIMARY KEY (IDConta_1, IDConta_2),

    CONSTRAINT FK_CONEXAO_PESSOAL1
        FOREIGN KEY (IDConta_1)
        REFERENCES PESSOAL(IDConta)
        ON DELETE CASCADE,

    CONSTRAINT FK_CONEXAO_PESSOAL2
        FOREIGN KEY (IDConta_2)
        REFERENCES PESSOAL(IDConta)
        ON DELETE CASCADE,

    CONSTRAINT CHK_CONEXAO_DIFERENTE
        CHECK (IDConta_1 <> IDConta_2)
);