DROP TABLE IF EXISTS PAIS CASCADE;
DROP TABLE IF EXISTS ESTADO CASCADE;
DROP TABLE IF EXISTS CIDADE CASCADE;
DROP TABLE IF EXISTS CONTA CASCADE;
DROP TABLE IF EXISTS PESSOAL CASCADE;
DROP TABLE IF EXISTS CORPORATIVA CASCADE;
DROP TABLE IF EXISTS CORPORATIVA_SETOREMP CASCADE;
DROP TABLE IF EXISTS COMPETENCIA CASCADE;
DROP TABLE IF EXISTS IDIOMA CASCADE;
DROP TABLE IF EXISTS FORMACAOACAD CASCADE;
DROP TABLE IF EXISTS EXPERIENCIAPROF CASCADE;
DROP TABLE IF EXISTS VAGAEMPREGO CASCADE;
DROP TABLE IF EXISTS POST CASCADE;
DROP TABLE IF EXISTS COMENTARIO CASCADE;
DROP TABLE IF EXISTS REAGEPOST CASCADE;
DROP TABLE IF EXISTS POSSCOMP CASCADE;
DROP TABLE IF EXISTS FORMPOSSCOMP CASCADE;
DROP TABLE IF EXISTS EXPPOSSCOMP CASCADE;
DROP TABLE IF EXISTS FALAIDIOM CASCADE;
DROP TABLE IF EXISTS APLICAAVAGA CASCADE;
DROP TABLE IF EXISTS CONEXAO CASCADE;

CREATE TABLE IF NOT EXISTS PAIS (
    IDPais INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NomPais VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ESTADO (
    IDEstado INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NomEstado VARCHAR(100) NOT NULL,
    fk_PAIS INT NOT NULL,

    CONSTRAINT FK_ESTADO_PAIS
        FOREIGN KEY (fk_PAIS)
        REFERENCES PAIS(IDPais)
);

CREATE TABLE IF NOT EXISTS CIDADE (
    IDCidade INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NomCidade VARCHAR(100) NOT NULL,
    fk_ESTADO INT NOT NULL,

    CONSTRAINT FK_CIDADE_ESTADO
        FOREIGN KEY (fk_ESTADO)
        REFERENCES ESTADO(IDEstado)
);

CREATE TABLE IF NOT EXISTS CONTA (
    IDConta INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EmailConta VARCHAR(255) UNIQUE NOT NULL,
    SenhaConta VARCHAR(255) NOT NULL,
    DtCrcaoConta DATE NOT NULL,
    fk_CIDADE INT,

    CONSTRAINT FK_CONTA_CIDADE
        FOREIGN KEY (fk_CIDADE)
        REFERENCES CIDADE(IDCidade)
);

CREATE TABLE IF NOT EXISTS PESSOAL (
    fk_CONTA INT PRIMARY KEY,
    NomPsso VARCHAR(100) NOT NULL,
    SobnomPsso VARCHAR(100) NOT NULL,
    TtloProfPsso VARCHAR(150),

    CONSTRAINT FK_PESSOAL_CONTA
        FOREIGN KEY (fk_CONTA)
        REFERENCES CONTA(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CORPORATIVA (
    fk_CONTA INT PRIMARY KEY,
    NomComerc VARCHAR(150) NOT NULL,
    NumFuncEmp INT,
    DescriEmp TEXT,

    CONSTRAINT FK_CORPORATIVA_CONTA
        FOREIGN KEY (fk_CONTA)
        REFERENCES CONTA(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CORPORATIVA_SETOREMP (
    SetorEmp VARCHAR(100) PRIMARY KEY,
    fk_CORPORATIVA INT NOT NULL,

    CONSTRAINT FK_SETOR_CORPORATIVA
        FOREIGN KEY (fk_CORPORATIVA)
        REFERENCES CORPORATIVA(fk_CONTA)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMPETENCIA (
    IDComp INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NomeComp VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS IDIOMA (
    IDIdioma INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NomeIdioma VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORMACAOACAD (
    IDForm INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NomInstitForm VARCHAR(150) NOT NULL,
    GrauForm VARCHAR(100),
    AreaForm VARCHAR(100),
    DtInicioForm DATE,
    DtFimForm DATE,
    fk_PESSOAL INT NOT NULL,

    CONSTRAINT FK_FORMACAO_PESSOAL
        FOREIGN KEY (fk_PESSOAL)
        REFERENCES PESSOAL(fk_CONTA)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EXPERIENCIAPROF (
    IDExp INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TituloExp VARCHAR(150) NOT NULL,
    TipoEmpregoExp VARCHAR(100),
    DtInicioExp DATE,
    DtFimExp DATE,
    DescAtv TEXT,
    fk_PESSOAL INT NOT NULL,
    fk_CORPORATIVA INT,

    CONSTRAINT FK_EXPERIENCIA_PESSOAL
        FOREIGN KEY (fk_PESSOAL)
        REFERENCES PESSOAL(fk_CONTA)
        ON DELETE CASCADE,

    CONSTRAINT FK_EXPERIENCIA_CORPORATIVA
        FOREIGN KEY (fk_CORPORATIVA)
        REFERENCES CORPORATIVA(fk_CONTA)
);

CREATE TABLE IF NOT EXISTS VAGAEMPREGO (
    IDVagaEmp INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TtloVaga VARCHAR(150) NOT NULL,
    DescriVaga TEXT,
    FormatoTrabVaga VARCHAR(50),
    DtCrcaoVaga DATE,
    fk_CORPORATIVA INT NOT NULL,

    CONSTRAINT FK_VAGA_CORPORATIVA
        FOREIGN KEY (fk_CORPORATIVA)
        REFERENCES CORPORATIVA(fk_CONTA)
        ON DELETE CASCADE
);

CREATE TABLE  IF NOT EXISTS POST (
    IDPost INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DtPubliPost TIMESTAMP NOT NULL,
    ConteudoPost TEXT NOT NULL,
    NivelVisib VARCHAR(50),
    fk_CONTA INT NOT NULL,

    CONSTRAINT FK_POST_CONTA
        FOREIGN KEY (fk_CONTA)
        REFERENCES CONTA(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMENTARIO (
    IDComentario INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ConteudoTxtCom TEXT NOT NULL,
    DtPubliCom TIMESTAMP NOT NULL,
    fk_POST INT NOT NULL,
    fk_CONTA INT NOT NULL,

    CONSTRAINT FK_COMENTARIO_POST
        FOREIGN KEY (fk_POST)
        REFERENCES POST(IDPost)
        ON DELETE CASCADE,

    CONSTRAINT FK_COMENTARIO_CONTA
        FOREIGN KEY (fk_CONTA)
        REFERENCES CONTA(IDConta)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REAGEPOST (
    DtReacao TIMESTAMP NOT NULL,
    TipoReacao VARCHAR(50) NOT NULL,
    fk_CONTA INT NOT NULL,
    fk_POST INT NOT NULL,

    PRIMARY KEY (fk_CONTA, fk_POST),

    CONSTRAINT FK_REAGEPOST_CONTA
        FOREIGN KEY (fk_CONTA)
        REFERENCES CONTA(IDConta)
        ON DELETE CASCADE,

    CONSTRAINT FK_REAGEPOST_POST
        FOREIGN KEY (fk_POST)
        REFERENCES POST(IDPost)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS POSSCOMP (
    fk_COMPETENCIA INT NOT NULL,
    fk_PESSOAL INT NOT NULL,

    PRIMARY KEY (fk_COMPETENCIA, fk_PESSOAL),

    CONSTRAINT FK_POSSCOMP_COMP
        FOREIGN KEY (fk_COMPETENCIA)
        REFERENCES COMPETENCIA(IDComp)
        ON DELETE CASCADE,

    CONSTRAINT FK_POSSCOMP_PESSOAL
        FOREIGN KEY (fk_PESSOAL)
        REFERENCES PESSOAL(fk_CONTA)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FORMPOSSCOMP (
    fk_COMPETENCIA INT NOT NULL,
    fk_FORMACAOACAD INT NOT NULL,

    PRIMARY KEY (fk_COMPETENCIA, fk_FORMACAOACAD),

    CONSTRAINT FK_FORMPOSSCOMP_COMP
        FOREIGN KEY (fk_COMPETENCIA)
        REFERENCES COMPETENCIA(IDComp)
        ON DELETE CASCADE,

    CONSTRAINT FK_FORMPOSSCOMP_FORM
        FOREIGN KEY (fk_FORMACAOACAD)
        REFERENCES FORMACAOACAD(IDForm)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS EXPPOSSCOMP (
    fk_COMPETENCIA INT NOT NULL,
    fk_EXPERIENCIAPROF INT NOT NULL,

    PRIMARY KEY (fk_COMPETENCIA, fk_EXPERIENCIAPROF),

    CONSTRAINT FK_EXPPOSSCOMP_COMP
        FOREIGN KEY (fk_COMPETENCIA)
        REFERENCES COMPETENCIA(IDComp)
        ON DELETE CASCADE,

    CONSTRAINT FK_EXPPOSSCOMP_EXP
        FOREIGN KEY (fk_EXPERIENCIAPROF)
        REFERENCES EXPERIENCIAPROF(IDExp)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FALAIDIOM (
    NvlProfic VARCHAR(50),
    fk_IDIOMA INT NOT NULL,
    fk_PESSOAL INT NOT NULL,

    PRIMARY KEY (fk_IDIOMA, fk_PESSOAL),

    CONSTRAINT FK_FALAIDIOM_IDIOMA
        FOREIGN KEY (fk_IDIOMA)
        REFERENCES IDIOMA(IDIdioma)
        ON DELETE CASCADE,

    CONSTRAINT FK_FALAIDIOM_PESSOAL
        FOREIGN KEY (fk_PESSOAL)
        REFERENCES PESSOAL(fk_CONTA)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS APLICAAVAGA (
    DtAplccao TIMESTAMP NOT NULL,
    SttusAplccao VARCHAR(50),
    fk_VAGAEMPREGO INT NOT NULL,
    fk_PESSOAL INT NOT NULL,

    PRIMARY KEY (fk_VAGAEMPREGO, fk_PESSOAL),

    CONSTRAINT FK_APLICA_VAGA
        FOREIGN KEY (fk_VAGAEMPREGO)
        REFERENCES VAGAEMPREGO(IDVagaEmp)
        ON DELETE CASCADE,

    CONSTRAINT FK_APLICA_PESSOAL
        FOREIGN KEY (fk_PESSOAL)
        REFERENCES PESSOAL(fk_CONTA)
        ON DELETE CASCADE
);

CREATE TABLE  IF NOT EXISTS CONEXAO (
    DtEnvConv TIMESTAMP NOT NULL,
    DtAceitConv TIMESTAMP,
    StatusConexao VARCHAR(50),
    fk_PESSOAL_1 INT NOT NULL,
    fk_PESSOAL_2 INT NOT NULL,

    PRIMARY KEY (fk_PESSOAL_1, fk_PESSOAL_2),

    CONSTRAINT FK_CONEXAO_PESSOAL1
        FOREIGN KEY (fk_PESSOAL_1)
        REFERENCES PESSOAL(fk_CONTA)
        ON DELETE CASCADE,

    CONSTRAINT FK_CONEXAO_PESSOAL2
        FOREIGN KEY (fk_PESSOAL_2)
        REFERENCES PESSOAL(fk_CONTA)
        ON DELETE CASCADE,

    CONSTRAINT CHK_CONEXAO_DIFERENTE
        CHECK (fk_PESSOAL_1 <> fk_PESSOAL_2)
);